services:
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf/
      - ./nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
      - ./letsencrypt/live/potesuch.ddns.net/fullchain.pem:/etc/letsencrypt/live/potesuch.ddns.net/fullchain.pem
      - ./letsencrypt/live/potesuch.ddns.net/privkey.pem:/etc/letsencrypt/live/potesuch.ddns.net/privkey.pem
  ngrok:
      image: ngrok/ngrok:latest
      ports:
        - "4041:4040"
      restart: unless-stopped
      command:
        - "start"
        - "--all"
        - "--config"
        - "/etc/ngrok.yml"
      volumes:
        - ./ngrok/ngrok.yml:/etc/ngrok.yml
      depends_on:
        - nginx
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6380:6379"
    volumes:
      - /var/lib/redis/data/
  bot:
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - ngrok
    env_file:
      - ./.env
