services:
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf/
  ngrok:
      image: ngrok/ngrok:latest
      ports:
        - "4040:4040"
      restart: unless-stopped
      command:
        - "start"
        - "--all"
        - "--config"
        - "/etc/ngrok.yml"
      volumes:
        - ./ngrok/ngrok.yml:/etc/ngrok.yml
      depends_on:
        - nginx
  redis:
    image: redis:7.2.4-alpine
    volumes:
      - /var/lib/redis/data/
  bot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - ngrok
    env_file:
      - ./.env
