services:
  nginx_kittybot:
    image: nginx:1.25.4-alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf/
      - ./letsencrypt/live/potesuch.ddns.net/fullchain.pem:/etc/letsencrypt/live/potesuch.ddns.net/fullchain.pem
      - ./letsencrypt/live/potesuch.ddns.net/privkey.pem:/etc/letsencrypt/live/potesuch.ddns.net/privkey.pem
#  ngrok_kittybot:
#      image: ngrok/ngrok:latest
#      ports:
#        - "4042:4040"
#      restart: unless-stopped
#      command:
#        - "start"
#        - "--all"
#        - "--config"
#        - "/etc/ngrok.yml"
#      volumes:
#        - ./ngrok/ngrok.yml:/etc/ngrok.yml
#      depends_on:
#        - nginx_kittybot
#      env_file:
#        - ./.env
  redis_kittybot:
    image: redis:7.2.4-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_storage_kittybot:/var/lib/redis/data/
  bot_kittybot:
    image: potesuch/kittybot
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - redis_kittybot
#      - ngrok_kittybot
    env_file:
      - ./.env

volumes:
  redis_storage_kittybot:
