name: kittybot CI
on: [push]
jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker
        uses: docker/build-push-action@v2
        with:
          context: ./bot
          push: True
          tags: potesuch/kittybot
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd kittybot/
            touch .env
            echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} > .env
            echo CAT_API=${{ secrets.CAT_API }} >> .env
            echo AI_CATS=${{ secrets.AI_CATS }} >> .env
            echo AI_PERSONS=${{ secrets.AI_PERSONS }} >> .env
            echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
            echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
            echo REDIS_DB=${{ secrets.REDIS_DB }} >> .env
            echo WEB_SERVER_HOST=${{ secrets.WEB_SERVER_HOST }} >> .env
            echo WEB_SERVER_PORT=${{ secrets.WEB_SERVER_PORT }} >> .env
            echo NGROK_AUTHTOKEN=${{ secrets.NGROK_AUTHTOKEN }} >> .env
            echo NGROK_HOST=${{ secrets.NGROK_HOST }} >> .env
            echo NGROK_PORT=${{ secrets.NGROK_PORT }} >> .env
            echo WEBHOOK_PATH=${{ secrets.WEBHOOK_PATH }} >> .env
            echo WEBHOOK_BASE_URL=${{ secrets.WEBHOOK_BASE_URL }} >> .env
            sudo docker compose down
            sudo docker compose pull bot_kittybot
            sudo docker compose up -d

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!
